"""Stacking and meta-learning utilities."""

from horse_lab.stacking.blend import (
    BlendSearchResult,
    ConvexBlendModel,
    blend_search_result_to_dict,
    search_convex_blend,
    search_convex_blend_from_csv,
)
from horse_lab.stacking.calibration import (
    CALIBRATED_PREDICTION_FIELDS,
    MarketCalibrationModel,
    MarketCalibrationStudyResult,
    market_calibration_study_result_to_dict,
    run_market_calibration_study,
    run_market_calibration_study_from_csv,
)
from horse_lab.stacking.meta_dataset import (
    META_DATASET_BASE_FIELDS,
    MetaDatasetBuildResult,
    build_meta_dataset,
    build_meta_dataset_from_csv,
    meta_dataset_build_result_to_dict,
    model_prediction_column,
)
from horse_lab.stacking.meta_learner import (
    META_PREDICTION_FIELDS,
    LogisticMetaModel,
    MetaFeatureRow,
    MetaLearnerTrainingResult,
    meta_learner_training_result_to_dict,
    read_meta_feature_rows,
    train_logistic_meta_learner,
    train_logistic_meta_learner_from_csv,
)
from horse_lab.stacking.phase4_study import (
    SEGMENT_METRIC_FIELDS,
    WALKFORWARD_PREDICTION_FIELDS,
    Phase4StudyResult,
    phase4_study_result_to_dict,
    run_phase4_study,
    run_phase4_study_from_csv,
)
from horse_lab.stacking.prediction_store import (
    OOF_PREDICTION_CSV_FIELDS,
    PredictionRole,
    StoredPrediction,
    model_prediction_to_stored_prediction,
    read_prediction_store_csv,
    stored_prediction_to_csv_row,
    write_prediction_store_csv,
)
from horse_lab.stacking.residual_overlay import (
    RESIDUAL_OVERLAY_PREDICTION_FIELDS,
    ResidualOverlayStudyResult,
    residual_overlay_study_result_to_dict,
    run_residual_overlay_study,
    run_residual_overlay_study_from_csv,
)
from horse_lab.stacking.segment_calibration import (
    SEGMENT_CALIBRATION_PREDICTION_FIELDS,
    SegmentCalibrationStudyResult,
    run_segment_calibration_study,
    run_segment_calibration_study_from_csv,
    segment_calibration_study_result_to_dict,
)

__all__ = [
    "BlendSearchResult",
    "ConvexBlendModel",
    "CALIBRATED_PREDICTION_FIELDS",
    "META_DATASET_BASE_FIELDS",
    "META_PREDICTION_FIELDS",
    "OOF_PREDICTION_CSV_FIELDS",
    "RESIDUAL_OVERLAY_PREDICTION_FIELDS",
    "SEGMENT_CALIBRATION_PREDICTION_FIELDS",
    "SEGMENT_METRIC_FIELDS",
    "WALKFORWARD_PREDICTION_FIELDS",
    "LogisticMetaModel",
    "MarketCalibrationModel",
    "MarketCalibrationStudyResult",
    "MetaFeatureRow",
    "MetaDatasetBuildResult",
    "MetaLearnerTrainingResult",
    "Phase4StudyResult",
    "PredictionRole",
    "ResidualOverlayStudyResult",
    "SegmentCalibrationStudyResult",
    "StoredPrediction",
    "build_meta_dataset",
    "build_meta_dataset_from_csv",
    "blend_search_result_to_dict",
    "meta_dataset_build_result_to_dict",
    "meta_learner_training_result_to_dict",
    "market_calibration_study_result_to_dict",
    "model_prediction_to_stored_prediction",
    "model_prediction_column",
    "read_meta_feature_rows",
    "read_prediction_store_csv",
    "phase4_study_result_to_dict",
    "residual_overlay_study_result_to_dict",
    "segment_calibration_study_result_to_dict",
    "run_phase4_study",
    "run_phase4_study_from_csv",
    "run_market_calibration_study",
    "run_market_calibration_study_from_csv",
    "run_residual_overlay_study",
    "run_residual_overlay_study_from_csv",
    "run_segment_calibration_study",
    "run_segment_calibration_study_from_csv",
    "search_convex_blend",
    "search_convex_blend_from_csv",
    "stored_prediction_to_csv_row",
    "train_logistic_meta_learner",
    "train_logistic_meta_learner_from_csv",
    "write_prediction_store_csv",
]
